Aller au contenu
Communauté DEV
Recherche...

Se connecter
Créer un compte

0
Aller aux commentaires
6
Sauvegarder

Image de couverture pour le déploiement d'une application Vite sur des pages GitHub à l'aide des actions GitHub : un guide étape par étape
Dauda Lawal
Dauda Lawal
Posté sur19 août • Mis à jour le2 sept.


5

1

1
Déployer une application Vite sur des pages GitHub à l'aide des actions GitHub : un guide étape par étape
#
développement web
#
réagir
#
développeur
#
github
Table des matières
Introduction
Conditions préalables
Configuration du projet
Configurer la configuration Vite
Déploiement de l'application
Apportez des modifications et poussez :
Flux de travail des actions GitHub :
Accès à l'application déployée :
Conclusion
Introduction
La création de flux de travail efficaces pour le déploiement d'applications Web est cruciale dans le paysage de développement actuel, en évolution rapide. Les pages GitHub et les actions GitHub sont devenues des outils puissants pour automatiser le processus de déploiement. Ce guide vise à guider les développeurs dans le déploiement d'une application Vite.js sur les pages GitHub à l'aide des actions GitHub.

À la fin de ce didacticiel, vous comprendrez parfaitement comment configurer un pipeline de déploiement automatisé pour votre application Vite.

Conditions préalables
Avant de nous lancer dans le processus de déploiement, assurons-nous que vous disposez des outils et des connaissances nécessaires :

Connaissance de Vite.js : Familiarité avec Vite.js, un outil de construction qui améliore considérablement l'expérience de développement des applications Web modernes.

Compte GitHub : Un compte GitHub est nécessaire pour créer des référentiels et configurer les actions GitHub.

Git : Compréhension de base de Git pour le contrôle de version.

Node.js et npm : assurez-vous que Node.js et npm (Node Package Manager) sont installés sur votre ordinateur.

Vite App : Une application Vite.js prête à être déployée.

Configuration du projet
Pour les besoins de ce guide, supposons que vous disposez d'une application Vite nommée « MyViteApp » que vous souhaitez déployer sur les pages GitHub.

Créez un référentiel GitHub :
accédez à votre compte GitHub et créez un nouveau référentiel nommé "my-vite-app" (ou tout autre nom de votre choix).
Clonez le référentiel sur votre machine locale à l'aide de git clone.

Configuration de l'application Vite :
accédez au répertoire de votre projet : cd my-vite-app.
Installer les dépendances : exécutez npm installpour installer les packages nécessaires.

Créez un workflow d'action GitHub :
dans votre référentiel, créez un nouveau répertoire nommé .github/workflows. Dans ce répertoire, créez un fichier YAML nommé deploy.yml. C'est ici que vous définirez votre workflow GitHub Actions.
Copiez et collez le code suivant dans votre deploy.ymlfichier :
# Simple workflow for deploying static content to GitHub Pages
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
Configurer la configuration Vite
Ajoutez une propriété appelée base avec la valeur du nom de notre référentiel sur vite.config.jsou vite.config.ts. Par exemple, si le nom de notre référentiel est my-vite-app, alors nous définissons la configuration comme suit :
// vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: '/my-vite-app/'
})

L'URL de déploiement seraithttps://<OUR_GITHUB_USERNAME>.github.io/my-vite-app.

Ce workflow s'exécutera à chaque poussée vers la branche principale. Il construira d'abord le projet, puis le déploiera sur les pages GitHub.

Déploiement de l'application
Une fois le workflow GitHub Actions en place, voici comment fonctionne le processus de déploiement :

Apporter des modifications et pousser :
apportez des modifications à votre application Vite. Validez et transmettez vos modifications à la branche principale. Validez le workflow de déploiement et transférez les modifications vers GitHub.
git add .
git commit -m "add deploy workflow"
git push


Workflow des actions GitHub :
les actions GitHub déclencheront automatiquement le workflow défini dans deploy.ymll'événement push.

Lorsque vous accédez à Actions et cliquez sur le workflow récent, vous devriez voir qu'il a échoué en raison d'autorisations manquantes :

autorisations

N'oubliez pas d'activer l'autorisation d'écriture. Pour résoudre ce problème, accédez à Paramètres d'actions , sélectionnez les autorisations de lecture et d'écriture et appuyez sur Enregistrer :

Autorisations de lecture et d'écriture
Revenez à Actions , cliquez sur le flux de travail ayant échoué et, dans le coin supérieur droit, cliquez sur Réexécuter les tâches ayant échoué.

échec du flux de travail

Accès à l'application déployée : une fois le flux de travail terminé avec succès, votre application Vite sera déployée sur l'URL des pages GitHub que vous avez spécifiées dans le champ de base avec la valeur du nom de notre référentiel sur vite.config.js. Accédez à votre application déployée sur https://yourusername.github.io/my-vite-app .
Conclusion
Toutes nos félicitations! Vous avez configuré avec succès un pipeline de déploiement automatisé pour votre application Vite.js à l'aide des actions GitHub et l'avez déployé sur les pages GitHub. Ce flux de travail rationalisé vous fera gagner du temps et des efforts, vous permettant de vous concentrer sur le développement d'applications Web étonnantes.

En suivant ce guide, vous avez acquis des informations précieuses sur la configuration des actions GitHub, la création d'un workflow de déploiement et l'utilisation des pages GitHub pour héberger vos projets. Ces connaissances vous permettront de rationaliser votre processus de développement et de déployer efficacement vos futures applications Web.

Merci de donner votre temps précieux!

🥰 Si vous avez aimé cet article, pensez à le partager.

Bon codage !

N'oubliez pas de déposer votre commentaire.

Meilleurs commentaires (0)

S'abonner
photo
Ajouter à la discussion
Code de conduite • Signaler un abus
Communauté DEV

Tendances dans Webdev
La communauté Webdev discute actuellement de l'importance des startups négligées et de leurs offres innovantes, de la maîtrise des composants React et de la préparation des entretiens avec les développeurs frontend de React. Il existe également un intérêt croissant pour les projets open source pour 2023 et l'apprentissage de l'IA en créant des réseaux de neurones à l'aide de Vanilla JS.

nathan_tarbert 
⚡⚡ 7 référentiels Open Source qui vous rendront 90 % plus intelligent 😎
Nathan Tarbert ・ 13 octobre
#webdev #programmation #opensource #productivité
GitHub 20k 
✨ 8 composants pour devenir un maître React 🧙‍♂️ 🪄
Nevo David pour GitHub 20k ・ 16 octobre
#réagir #webdev #javascript #opensource
m_midas 
44 questions d'entretien avec React Frontend
Yan Levin ・ 12 octobre
#webdev #javascript #débutants #react
madza 
24 projets Open Source pour les développeurs en 2023 🔥👍
Madza ・ 17 octobre
#opensource #github #programmation #webdev
grahamthedev 
🧠 Une IA/réseau de neurones...en vanilla JS ! 😱 Sans bibliothèques ! 🤯
GrahamTheDev ・ 13 octobre
#ai #javascript #débutants #webdev
Lire ensuite
image de profil de samanabbasi
🚀Comment fonctionne JavaScript (partie 8) ? Obligatoire
Sam Abaasi-26 octobre

image de profil de Wilsmex
Tutoriel CSS Flexbox
SuivreAndrew -26 octobre

image de profil de lakshmananarumugam
Gestion avancée des URL Next.js avec URLSearchParams
Lakshmanan Arumugam -26 octobre

documentécrit l'image de profil
Million.js : audit de documents en 10 minutes
DocumentÉcrire -12 octobre


Dauda Lawal
Suivre
Développeur Web| Rédacteur technique| Passionné de blockchain
EMPLACEMENT
Lagos, Nigéria
REJOINT
3 juillet. 2022
Plus de Dauda Lawal
Commandes Git essentielles : Top 5 que chaque développeur doit maîtriser
# webdev # programmation # github # débutants
Comprendre la différence entre les types de données primitifs et non primitifs en JavaScript
# webdev # javascript # débutants # programmation
Qu'est-ce que les espaces de codes GitHub ?
# débutants # programmation # github # githubhack23
Communauté DEV

🌚 La vie est trop courte pour naviguer sans mode sombre
Vous pouvez personnaliser votre thème, votre police et bien plus encore lorsque vous êtes connecté .

# Simple workflow for deploying static content to GitHub Pages
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
